### PR TITLE
use example based on start.spring.io

### PR DESCRIPTION
**Pull request by kadel**

### CODE REVIEW

**Comment by kadel** [comment]
what do you think @johnmcollier @maysunfaisal ?

**Review by maysunfaisal — APPROVED** [review]
I like this. Its a template from the official template and gets rid off all the IBM placeholders that were unnecessary.

Tested and works great!

**Comment by johnmcollier** [comment]
Looks good to me too.

Do we need to update the tests in the registry repo too?

https://github.com/odo-devfiles/registry/blob/96d049cbde523b141e3ddc51c38722485bdc735e/scripts/test.sh#L150

**Review by johnmcollier — COMMENTED** [review]
Looks good to me too, but I think we need to update the test case for spring in the https://github.com/odo-devfiles/registry repo too:

https://github.com/odo-devfiles/registry/blob/master/scripts/test.sh#L153

**Comment by kadel** [comment]
> Looks good to me too, but once this is merged, we need to update the test case for spring in the https://github.com/odo-devfiles/registry repo too:
> 
> https://github.com/odo-devfiles/registry/blob/master/scripts/test.sh#L153

good catch. I'll take care of it.

**Pull request merged**
